import { decimal, int, mysqlEnum, mysqlTable, text, timestamp, unique, varchar, index } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "merchant", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const stores = mysqlTable("pediu_stores", { id: int("id").autoincrement().primaryKey(), ownerId: int("ownerId").notNull(), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 32 }), address: varchar("address", { length: 255 }), pixKey: varchar("pixKey", { length: 255 }), deliveryFee: decimal("deliveryFee", { precision: 10, scale: 2 }).default("0.00").notNull(), isOpen: int("isOpen").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ ownerUnique: unique("pediu_stores_owner_unique").on(t.ownerId), openIdx: index("pediu_stores_open_idx").on(t.isOpen) }));
export const products = mysqlTable("pediu_products", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), name: varchar("name", { length: 180 }).notNull(), category: varchar("category", { length: 80 }).notNull(), description: text("description"), price: decimal("price", { precision: 10, scale: 2 }).notNull(), available: int("available").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const orders = mysqlTable("pediu_orders", { id: int("id").autoincrement().primaryKey(), customerId: int("customerId").notNull(), storeId: int("storeId").notNull(), status: mysqlEnum("status", ["Pendente", "Aceito", "Preparando", "Pronto", "A caminho", "Entregue", "Cancelado"]).default("Pendente").notNull(), total: decimal("total", { precision: 10, scale: 2 }).notNull(), deliveryAddress: varchar("deliveryAddress", { length: 255 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => ({ customerCreatedIdx: index("pediu_orders_customer_created_idx").on(t.customerId, t.createdAt), storeStatusCreatedIdx: index("pediu_orders_store_status_created_idx").on(t.storeId, t.status, t.createdAt) }));
export const orderItems = mysqlTable("pediu_order_items", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), productId: int("productId").notNull(), quantity: int("quantity").default(1).notNull(), unitPrice: decimal("unitPrice", { precision: 10, scale: 2 }).notNull() }, t => ({ orderIdx: index("pediu_order_items_order_idx").on(t.orderId) }));
export const payments = mysqlTable("pediu_payments", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), method: mysqlEnum("method", ["pix", "card", "cash", "fiado"]).default("pix").notNull(), status: mysqlEnum("status", ["pending", "paid", "failed", "cancelled"]).default("pending").notNull(), pixKey: varchar("pixKey", { length: 255 }), transactionId: varchar("transactionId", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ transactionUnique: unique("pediu_payments_transaction_unique").on(t.transactionId), orderStatusIdx: index("pediu_payments_order_status_idx").on(t.orderId, t.status) }));
export const paymentAccounts = mysqlTable("pediu_payment_accounts", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), provider: varchar("provider", { length: 40 }).notNull(), providerAccountId: varchar("providerAccountId", { length: 160 }), onboardingStatus: mysqlEnum("onboardingStatus", ["pending", "active", "restricted", "disabled"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => ({ storeUnique: unique("pediu_payment_accounts_store_unique").on(t.storeId), providerAccountUnique: unique("pediu_payment_accounts_provider_account_unique").on(t.provider, t.providerAccountId) }));
export const paymentTransactions = mysqlTable("pediu_payment_transactions", { id: int("id").autoincrement().primaryKey(), paymentId: int("paymentId").notNull(), provider: varchar("provider", { length: 40 }).notNull(), providerTransactionId: varchar("providerTransactionId", { length: 160 }), status: mysqlEnum("status", ["pending", "authorized", "paid", "failed", "refunded", "cancelled"]).default("pending").notNull(), amount: decimal("amount", { precision: 10, scale: 2 }).notNull(), gatewayFee: decimal("gatewayFee", { precision: 10, scale: 2 }).default("0.00").notNull(), currency: varchar("currency", { length: 3 }).default("BRL").notNull(), idempotencyKey: varchar("idempotencyKey", { length: 160 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => ({ providerTransactionUnique: unique("pediu_payment_transactions_provider_tx_unique").on(t.provider, t.providerTransactionId), idempotencyUnique: unique("pediu_payment_transactions_idempotency_unique").on(t.provider, t.idempotencyKey) }));
export const commissionRules = mysqlTable("pediu_commission_rules", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId"), type: mysqlEnum("type", ["percentage", "fixed", "hybrid"]).notNull(), percentage: decimal("percentage", { precision: 7, scale: 4 }).default("0.0000").notNull(), fixedAmount: decimal("fixedAmount", { precision: 10, scale: 2 }).default("0.00").notNull(), activeFrom: timestamp("activeFrom").defaultNow().notNull(), activeUntil: timestamp("activeUntil"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const commissionEntries = mysqlTable("pediu_commission_entries", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), paymentId: int("paymentId"), ruleId: int("ruleId"), grossAmount: decimal("grossAmount", { precision: 10, scale: 2 }).notNull(), commissionAmount: decimal("commissionAmount", { precision: 10, scale: 2 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const financialLedger = mysqlTable("pediu_financial_ledger", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), orderId: int("orderId"), paymentId: int("paymentId"), type: mysqlEnum("type", ["sale", "gateway_fee", "commission", "receivable", "payout", "refund", "adjustment"]).notNull(), direction: mysqlEnum("direction", ["credit", "debit"]).notNull(), amount: decimal("amount", { precision: 10, scale: 2 }).notNull(), currency: varchar("currency", { length: 3 }).default("BRL").notNull(), referenceId: varchar("referenceId", { length: 160 }), note: varchar("note", { length: 255 }), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const payouts = mysqlTable("pediu_payouts", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), provider: varchar("provider", { length: 40 }).notNull(), providerPayoutId: varchar("providerPayoutId", { length: 160 }), status: mysqlEnum("status", ["pending", "processing", "paid", "failed", "cancelled"]).default("pending").notNull(), grossAmount: decimal("grossAmount", { precision: 10, scale: 2 }).notNull(), fees: decimal("fees", { precision: 10, scale: 2 }).default("0.00").notNull(), netAmount: decimal("netAmount", { precision: 10, scale: 2 }).notNull(), currency: varchar("currency", { length: 3 }).default("BRL").notNull(), scheduledAt: timestamp("scheduledAt"), paidAt: timestamp("paidAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ providerPayoutUnique: unique("pediu_payouts_provider_payout_unique").on(t.provider, t.providerPayoutId) }));
export const refunds = mysqlTable("pediu_refunds", { id: int("id").autoincrement().primaryKey(), paymentId: int("paymentId").notNull(), orderId: int("orderId").notNull(), provider: varchar("provider", { length: 40 }).notNull(), providerRefundId: varchar("providerRefundId", { length: 160 }), status: mysqlEnum("status", ["pending", "processing", "refunded", "failed"]).default("pending").notNull(), amount: decimal("amount", { precision: 10, scale: 2 }).notNull(), reason: varchar("reason", { length: 255 }), createdAt: timestamp("createdAt").defaultNow().notNull(), completedAt: timestamp("completedAt"), }, t => ({ providerRefundUnique: unique("pediu_refunds_provider_refund_unique").on(t.provider, t.providerRefundId) }));
export const webhookEvents = mysqlTable("pediu_webhook_events", { id: int("id").autoincrement().primaryKey(), provider: varchar("provider", { length: 40 }).notNull(), providerEventId: varchar("providerEventId", { length: 160 }).notNull(), eventType: varchar("eventType", { length: 100 }).notNull(), status: mysqlEnum("status", ["received", "processed", "ignored", "failed"]).default("received").notNull(), payload: text("payload"), processedAt: timestamp("processedAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ providerEventUnique: unique("pediu_webhook_events_provider_event_unique").on(t.provider, t.providerEventId) }));
export const customers = mysqlTable("pediu_customers", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), userId: int("userId"), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 32 }), notes: text("notes"), creditLimit: decimal("creditLimit", { precision: 10, scale: 2 }).default("0.00").notNull(), balance: decimal("balance", { precision: 10, scale: 2 }).default("0.00").notNull(), status: mysqlEnum("status", ["active", "blocked"]).default("active").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ userStoreUnique: unique("pediu_customers_store_user_unique").on(t.storeId, t.userId), storeIdx: index("pediu_customers_store_idx").on(t.storeId) }));
export const ledgerEntries = mysqlTable("pediu_ledger_entries", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), customerId: int("customerId").notNull(), orderId: int("orderId"), type: mysqlEnum("type", ["credit", "payment", "adjustment", "reversal"]).notNull(), amount: decimal("amount", { precision: 10, scale: 2 }).notNull(), balanceAfter: decimal("balanceAfter", { precision: 10, scale: 2 }), note: varchar("note", { length: 255 }), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ storeCustomerCreatedIdx: index("pediu_ledger_store_customer_created_idx").on(t.storeId, t.customerId, t.createdAt) }));
export const sales = mysqlTable("pediu_sales", { id: int("id").autoincrement().primaryKey(), storeId: int("storeId").notNull(), customerId: int("customerId"), orderId: int("orderId"), total: decimal("total", { precision: 10, scale: 2 }).notNull(), paymentMethod: varchar("paymentMethod", { length: 40 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = mysqlTable("pediu_notifications", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), title: varchar("title", { length: 160 }).notNull(), body: text("body").notNull(), type: varchar("type", { length: 60 }).notNull(), read: int("read").default(0).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const pushTokens = mysqlTable("pediu_push_tokens", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), token: varchar("token", { length: 512 }).notNull().unique(), platform: varchar("platform", { length: 20 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const adminAuditLogs = mysqlTable("pediu_admin_audit_logs", { id: int("id").autoincrement().primaryKey(), adminUserId: int("adminUserId").notNull(), action: varchar("action", { length: 100 }).notNull(), entityType: varchar("entityType", { length: 60 }).notNull(), entityId: varchar("entityId", { length: 120 }), metadata: text("metadata"), createdAt: timestamp("createdAt").defaultNow().notNull() });

export const customerAddresses = mysqlTable("pediu_customer_addresses", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), label: varchar("label", { length: 40 }).notNull(), recipientName: varchar("recipientName", { length: 160 }).notNull(), street: varchar("street", { length: 180 }).notNull(), number: varchar("number", { length: 30 }).notNull(), complement: varchar("complement", { length: 120 }), neighborhood: varchar("neighborhood", { length: 100 }).notNull(), city: varchar("city", { length: 100 }).notNull(), state: varchar("state", { length: 2 }).notNull(), postalCode: varchar("postalCode", { length: 8 }).notNull(), latitude: decimal("latitude", { precision: 10, scale: 7 }), longitude: decimal("longitude", { precision: 10, scale: 7 }), isDefault: int("isDefault").default(0).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => ({ userIdx: index("pediu_customer_addresses_user_idx").on(t.userId), userDefaultIdx: index("pediu_customer_addresses_user_default_idx").on(t.userId, t.isDefault) }));
